version: '3.4'

x-env:
  &env
  NGINX_SERVER_NAME: "$NGINX_SERVER_NAME"
  NGINX_EMAIL: "$NGINX_EMAIL"
  BRIDGE_VERSION: "$BRIDGE_VERSION"
  FEDERATION_VERSION: "$FEDERATION_VERSION"
  COMPLIANCE_VERSION: "$COMPLIANCE_VERSION"
  BRIDGE_PORT: "$BRIDGE_PORT"
  FEDERATION_PORT: "$FEDERATION_PORT"
  COMPLIANCE_EXTERNAL_PORT: "$COMPLIANCE_EXTERNAL_PORT"
  COMPLIANCE_INTERNAL_PORT: "$COMPLIANCE_INTERNAL_PORT"
  COMPLIANCE_NODE_PORT: "$COMPLIANCE_NODE_PORT"
  LEDGER_PORT: "$LEDGER_PORT"
  HORIZON: "$HORIZON"
  PASSPHRASE: "$PASSPHRASE"
  FEDERATION_URL: "$FEDERATION_URL"
  COMPLIANCE_URL: "$COMPLIANCE_URL"
  RECEIVE_URL: "$RECEIVE_URL"
  ISSUER: "$ISSUER"
  RECEIVING_ACCOUNT: "$RECEIVING_ACCOUNT"
  BASE_SEED: "$BASE_SEED"
  SIGNING_SEED: "$SIGNING_SEED"
  ENCRYPTION_KEY: "$ENCRYPTION_KEY"
  SANCTIONS_URL: "$SANCTIONS_URL"
  ASK_USER_URL: "$ASK_USER_URL"
  FETCH_INFO_URL: "$FETCH_INFO_URL"
  IMAGE_URL: "$IMAGE_URL"
  CURRENCY_CODE: "$CURRENCY_CODE"
  CONDITIONS: "$CONDITIONS"
  DESC: "$DESC"
  DECIMALS: "$DECIMALS"
  CREATE_ACCOUNTS_TABLE: "$CREATE_ACCOUNTS_TABLE"
  POPULATE_ACCOUNTS_TABLE: "$POPULATE_ACCOUNTS_TABLE"
  STAGING: "$STAGING"

networks:
  federation:

services:
  stellaranchor:
    image: ${DOCKER_REGISTRY-}stellaranchor
    build:
      context: .
      dockerfile: StellarAnchor/Dockerfile
    depends_on:
      - db
      - bridge
      - compliance
      #- federation
      #- ledger
    networks:
      - federation

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: StellarAnchor
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    networks:
      - federation

  bridge:
    container_name: bridge
    build:  
      context: Bridge
      args:
        BRIDGE_VERSION: ${BRIDGE_VERSION}
    networks:
      - federation
    depends_on:
      - bridge_db
    environment:
      DB_TYPE: mysql
      DB_URI: dbuser:${BRIDGE_DB_PASSWORD}@/stellar_bridge

  bridge_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: stellar_bridge
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: ${BRIDGE_DB_PASSWORD}
    networks:
      - federation

  compliance:
    container_name: compliance
    build:  
      context: Compliance
      args:
        COMPLIANCE_VERSION: ${COMPLIANCE_VERSION}
    depends_on:
      - compliance_db
    environment:
      DB_TYPE: mysql
      DB_URI: dbuser:${COMPLIANCE_DB_PASSWORD}@/stellar_compliance

  compliance_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: stellar_compliance
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: ${COMPLIANCE_DB_PASSWORD}
    networks:
      - federation

  federation:
    container_name: federation
    build:  
      context: Federation
      args:
        FEDERATION_VERSION: ${FEDERATION_VERSION}
    depends_on:
      - federation_db
    environment:
      DB_TYPE: mysql
      DB_URI: dbuser:${FEDERATION_DB_PASSWORD}@/stellar_federation

  federation_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: stellar_federation
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: ${FEDERATION_DB_PASSWORD}
    networks:
      - federation